using foodtopia.Models;

namespace foodtopia.Database.Seeds
{
    public static class CountrySeed
    {
        public static IEnumerable<Country> GetCountries()
        {
            return new List<Country>
            {
                new Country { Id = Guid.NewGuid(), Name = "Afghanistan", ImagePath = "images/flags/afghanistan.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Albania", ImagePath = "images/flags/albania.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Algeria", ImagePath = "images/flags/algeria.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Andorra", ImagePath = "images/flags/andorra.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Angola", ImagePath = "images/flags/angola.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Antigua & Barbuda", ImagePath = "images/flags/antigua_barbuda.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Argentina", ImagePath = "images/flags/argentina.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Armenia", ImagePath = "images/flags/armenia.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Australia", ImagePath = "images/flags/australia.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Austria", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Azerbaijan", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Bahamas", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Bangladesh", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Barbados", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Belgium", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Belize", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Bolivia", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Brazil", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Cameroon", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Canada", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Chile", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "China", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Colombia", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Costa Rica", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Croatia", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Cuba", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Denmark", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Dominican Republic", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Ecuador", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Egypt", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "El Salvador", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Fiji", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Finland", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "France", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Germany", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Ghana", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Greece", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Guatemala", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Hungary", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Iceland", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "India", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Ireland", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Israel", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Italy", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Jamaica", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Japan", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Kosovo", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Kuwait", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Lithuania", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Madagascar", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Malaysia", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Maldives", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Malta", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Mexico", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Monaco", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Morocco", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Nepal", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Netherlands", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "New Zealand", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Nigeria", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Norway", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Pakistan", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Palestine", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Panama", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Peru", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Philippines", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Poland", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Portugal", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Qatar", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Russia", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "St. Kitts & Nevis", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Saudi Arabia", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Serbia", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "South Africa", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "South Korea", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Spain", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Sweden", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Thailand", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Trinidad & Tobago", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Turkey", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Ukraine", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "UAE", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "UK", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "USA", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Venezuela", ImagePath = "images/flags/.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Vietnam", ImagePath = "images/flags/.svg"}
            };
        }
    }
}