using foodtopia.Models;

namespace foodtopia.Database.Seeds
{
    public static class CountrySeed
    {
        public static IEnumerable<Country> GetCountries()
        {
            return new List<Country>
            {
                new Country { Id = Guid.NewGuid(), Name = "Afghanistan", Slug = "afghanistan", ImagePath = "images/flags/afghanistan.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Albania", Slug = "albania", ImagePath = "images/flags/albania.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Algeria", Slug = "algeria", ImagePath = "images/flags/algeria.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Andorra", Slug = "andorra", ImagePath = "images/flags/andorra.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Angola", Slug = "angola", ImagePath = "images/flags/angola.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Antigua & Barbuda", Slug = "antigua-and-barbuda", ImagePath = "images/flags/antigua_barbuda.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Argentina", Slug = "argentina", ImagePath = "images/flags/argentina.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Armenia", Slug = "armenia", ImagePath = "images/flags/armenia.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Australia", Slug = "australia", ImagePath = "images/flags/australia.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Austria", Slug = "austria", ImagePath = "images/flags/austria.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Azerbaijan", Slug = "azerbaijan", ImagePath = "images/flags/azerbaijan.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Bahamas", Slug = "bahamas", ImagePath = "images/flags/bahamas.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Belgium", Slug = "belgium", ImagePath = "images/flags/belgium.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Bolivia", Slug = "bolivia", ImagePath = "images/flags/bolivia.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Brazil", Slug = "brazil", ImagePath = "images/flags/brazil.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Cameroon", Slug = "cameroon", ImagePath = "images/flags/cameroon.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Canada", Slug = "canada", ImagePath = "images/flags/canada.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Chile", Slug = "chile", ImagePath = "images/flags/chile.svg"},
                new Country { Id = Guid.NewGuid(), Name = "China", Slug = "china", ImagePath = "images/flags/china.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Colombia", Slug = "colombia", ImagePath = "images/flags/colombia.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Costa Rica", Slug = "costa-rica", ImagePath = "images/flags/costa_rica.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Croatia", Slug = "croatia", ImagePath = "images/flags/croatia.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Cuba", Slug = "cuba", ImagePath = "images/flags/cuba.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Denmark", Slug = "denmark", ImagePath = "images/flags/denmark.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Dominican Republic", Slug = "dominica-republic", ImagePath = "images/flags/dominican_republic.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Ecuador", Slug = "ecuador", ImagePath = "images/flags/ecuador.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Egypt", Slug = "egypt", ImagePath = "images/flags/egypt.svg"},
                new Country { Id = Guid.NewGuid(), Name = "El Salvador", Slug = "el-salvador", ImagePath = "images/flags/el_salvador.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Fiji", Slug = "fiji", ImagePath = "images/flags/fiji.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Finland", Slug = "finland", ImagePath = "images/flags/finland.svg"},
                new Country { Id = Guid.NewGuid(), Name = "France", Slug = "france", ImagePath = "images/flags/france.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Germany", Slug = "germany", ImagePath = "images/flags/germany.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Ghana", Slug = "ghana", ImagePath = "images/flags/ghana.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Greece", Slug = "greece", ImagePath = "images/flags/greece.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Guatemala", Slug = "guatemala", ImagePath = "images/flags/guatemala.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Hungary", Slug = "hungary", ImagePath = "images/flags/hungary.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Iceland", Slug = "iceland", ImagePath = "images/flags/iceland.svg"},
                new Country { Id = Guid.NewGuid(), Name = "India", Slug = "india", ImagePath = "images/flags/india.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Ireland", Slug = "ireland", ImagePath = "images/flags/ireland.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Israel", Slug = "israel", ImagePath = "images/flags/israel.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Italy", Slug = "italy", ImagePath = "images/flags/italy.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Jamaica", Slug = "jamaica", ImagePath = "images/flags/jamaica.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Japan", Slug = "japan", ImagePath = "images/flags/japan.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Kosovo", Slug = "kosovo", ImagePath = "images/flags/kosovo.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Kuwait", Slug = "kuwait", ImagePath = "images/flags/kuwait.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Mexico", Slug = "mexico", ImagePath = "images/flags/mexico.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Monaco", Slug = "monaco", ImagePath = "images/flags/monaco.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Morocco", Slug = "morocco", ImagePath = "images/flags/morocco.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Netherlands", Slug = "netherlands", ImagePath = "images/flags/netherlands.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Nigeria", Slug = "nigeria", ImagePath = "images/flags/nigeria.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Norway", Slug = "norway", ImagePath = "images/flags/norway.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Pakistan", Slug = "pakistan", ImagePath = "images/flags/pakistan.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Palestine", Slug = "palestine", ImagePath = "images/flags/palestine.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Panama", Slug = "panama", ImagePath = "images/flags/panama.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Peru", Slug = "peru", ImagePath = "images/flags/peru.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Philippines", Slug = "philippines", ImagePath = "images/flags/philippines.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Poland", Slug = "poland", ImagePath = "images/flags/poland.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Portugal", Slug = "portugal", ImagePath = "images/flags/portugal.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Qatar", Slug = "qatar", ImagePath = "images/flags/qatar.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Russia", Slug = "russia", ImagePath = "images/flags/russia.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Saudi Arabia", Slug = "saudi-arabia", ImagePath = "images/flags/saudi_arabia.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Serbia", Slug = "serbia", ImagePath = "images/flags/serbia.svg"},
                new Country { Id = Guid.NewGuid(), Name = "South Africa", Slug = "south-africa", ImagePath = "images/flags/south_africa.svg"},
                new Country { Id = Guid.NewGuid(), Name = "South Korea", Slug = "south-korea", ImagePath = "images/flags/south_korea.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Spain", Slug = "spain", ImagePath = "images/flags/spain.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Sweden", Slug = "sweden", ImagePath = "images/flags/sweden.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Thailand", Slug = "thailand", ImagePath = "images/flags/thailand.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Trinidad & Tobago", Slug = "trinidad-and-tobago", ImagePath = "images/flags/trinidad&tobago.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Turkey", Slug = "turkey", ImagePath = "images/flags/turkey.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Ukraine", Slug = "ukraine", ImagePath = "images/flags/ukraine.svg"},
                new Country { Id = Guid.NewGuid(), Name = "UAE", Slug = "united-arab-emirates", ImagePath = "images/flags/uae.svg"},
                new Country { Id = Guid.NewGuid(), Name = "UK", Slug = "united-kingdom", ImagePath = "images/flags/uk.svg"},
                new Country { Id = CountrySeedUUID.USA, Name = "USA", Slug = "usa", ImagePath = "images/flags/usa.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Venezuela", Slug = "venezuela", ImagePath = "images/flags/venezuela.svg"},
                new Country { Id = Guid.NewGuid(), Name = "Vietnam", Slug = "vietnam", ImagePath = "images/flags/vietnam.svg"}
            };
        }
    }
}