// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using foodtopia.Database;

#nullable disable

namespace foodtopia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241129191443_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("foodtopia.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b55196d-e481-439f-a800-8d7b241cce15"),
                            ImagePath = "images/flags/",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("35320a7c-2871-48fb-803b-8605e8c13f7a"),
                            ImagePath = "images/flags/",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("6e5249f6-24d8-4c91-81ec-8edd4977f1e1"),
                            ImagePath = "images/flags/",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("5dec25ff-c37e-411a-925d-87a13c22865c"),
                            ImagePath = "images/flags/",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("1b537870-67ef-4a3a-b329-76ac59385ea7"),
                            ImagePath = "images/flags/",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("09ca6521-384e-4b6d-a689-5f5012f11919"),
                            ImagePath = "images/flags/",
                            Name = "Antigua & Barbuda"
                        },
                        new
                        {
                            Id = new Guid("31c49f1a-58e2-475b-b7c0-f24060e11f1f"),
                            ImagePath = "images/flags/",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("819993b4-2608-4713-adae-f6dc31c96404"),
                            ImagePath = "images/flags/",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("3d6d8e11-1494-4c97-afb4-25915f3b0bf3"),
                            ImagePath = "images/flags/",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("e1ae35f7-b39c-46ce-8963-e4837c512244"),
                            ImagePath = "images/flags/",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("72c2be61-ef49-4a2e-b1d8-29051ebc84ee"),
                            ImagePath = "images/flags/",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("bc61ed18-2304-4fe6-b7ed-24549bf4b69d"),
                            ImagePath = "images/flags/",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("9483c8e7-c416-4e22-bc93-fae0a6d79040"),
                            ImagePath = "images/flags/",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("09d0ab82-09f0-40ee-8b29-2c2319d29d75"),
                            ImagePath = "images/flags/",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("1659ba44-39b4-45a4-acaa-6f73bbc635ed"),
                            ImagePath = "images/flags/",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("3c0e48c9-f620-42db-a674-411690c12682"),
                            ImagePath = "images/flags/",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("603c264d-202e-451a-9bb0-a1090e372a26"),
                            ImagePath = "images/flags/",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("ac09101e-0f9a-457c-b5c1-fb23f7b44f87"),
                            ImagePath = "images/flags/",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("f67f1c9f-9a42-43d4-a27e-09b45fd30125"),
                            ImagePath = "images/flags/",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("74f5c018-bb88-4e4f-8bc5-30cda421229e"),
                            ImagePath = "images/flags/",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("15341fbf-9191-407b-b72f-f642e1a813c1"),
                            ImagePath = "images/flags/",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("fd5bdb39-365b-4338-adb1-af2e9d20b4f3"),
                            ImagePath = "images/flags/",
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("fcedc254-c22c-43af-8d9a-68db9d5496ec"),
                            ImagePath = "images/flags/",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("c43d2a02-229b-49c6-a247-778e600f4069"),
                            ImagePath = "images/flags/",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("a5f1ce9d-eaab-4835-a7e8-931cc15b7ca1"),
                            ImagePath = "images/flags/",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("86a4c6cd-276a-427b-b18d-eb6ff1d02112"),
                            ImagePath = "images/flags/",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("2700574b-325d-4729-bf51-34181a7fc9a5"),
                            ImagePath = "images/flags/",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("0d1ae416-d9f2-4458-8350-ec87b452b081"),
                            ImagePath = "images/flags/",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("c9571bbf-8ede-4f04-9766-ca5cd510c975"),
                            ImagePath = "images/flags/",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("eb6c92c3-53d9-4b59-b821-0c5fb010bbfd"),
                            ImagePath = "images/flags/",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("94d36556-0b7b-4651-8def-e10dd7690ae6"),
                            ImagePath = "images/flags/",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("1a871b1e-ecbc-4628-9b10-6f9f8389e5f9"),
                            ImagePath = "images/flags/",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("b8237004-226f-4300-b37d-5aecc635eb02"),
                            ImagePath = "images/flags/",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("fbb45dcd-a086-4f72-ae82-18bc840c6f12"),
                            ImagePath = "images/flags/",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("29f6b556-3bbd-450f-a665-c7932cde5072"),
                            ImagePath = "images/flags/",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("158e4d2e-c671-4ca0-b59b-10245eefe159"),
                            ImagePath = "images/flags/",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("87656d76-e254-45d6-8f1f-0bbfb2cf66fe"),
                            ImagePath = "images/flags/",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("1dc6fc92-b974-4254-b44f-3751b9e2ff15"),
                            ImagePath = "images/flags/",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("a1db2b32-b036-4beb-8e85-22a24abf1124"),
                            ImagePath = "images/flags/",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("5e3a7296-2e15-4ef0-8673-1b1519cafe1e"),
                            ImagePath = "images/flags/",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("1ea87b72-f6dc-4ae7-8178-680a00e35209"),
                            ImagePath = "images/flags/",
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("7aacc2ab-d361-4bf9-a433-34e26085b924"),
                            ImagePath = "images/flags/",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("e6e239f9-e494-48ab-bba8-e961b155a37c"),
                            ImagePath = "images/flags/",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("54ffa9e4-4da7-48b8-bc54-ceb3edb6666f"),
                            ImagePath = "images/flags/",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("a125479c-8ceb-415d-b3cd-a2a787584020"),
                            ImagePath = "images/flags/",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("6cc7411d-aa6c-4db6-86c2-8526691f0a3b"),
                            ImagePath = "images/flags/",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("5c5a5cdc-b4c3-410b-9a32-b51299dcd8ef"),
                            ImagePath = "images/flags/",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("2b676304-23f9-4091-b3b5-cc4db007c6e2"),
                            ImagePath = "images/flags/",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("e7a46b4c-a4d2-41f0-9e7a-109c35308ee4"),
                            ImagePath = "images/flags/",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("d28a0fab-65c7-4f86-98a2-68efaa1410ae"),
                            ImagePath = "images/flags/",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("166a0e70-f3a4-4eb1-8137-67196574afbe"),
                            ImagePath = "images/flags/",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("e537ac8f-beca-4b5a-968c-d2fb7d01112e"),
                            ImagePath = "images/flags/",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("b51eb071-9ae4-4155-b718-0fca506fa295"),
                            ImagePath = "images/flags/",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("d2eda5c7-748e-4c2f-b422-63226be1ffca"),
                            ImagePath = "images/flags/",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("393d2ef0-1c9e-46e2-bc5e-8659d772f610"),
                            ImagePath = "images/flags/",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("57e9c9d8-7875-4b03-9cda-4bd56910a2d1"),
                            ImagePath = "images/flags/",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("e85d4770-d29b-4d7d-af22-df98c77e792c"),
                            ImagePath = "images/flags/",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("9bbd9235-2a37-4808-a01a-207686becf65"),
                            ImagePath = "images/flags/",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("9bbcb356-8d1c-43a9-a35e-574106dd3de4"),
                            ImagePath = "images/flags/",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("65693655-2028-4828-86f2-4b3d53adc629"),
                            ImagePath = "images/flags/",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("15280df4-afa5-4180-a888-32827c8b6a5c"),
                            ImagePath = "images/flags/",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("fc5557e2-e595-4b67-b6a8-64f1dbfc1444"),
                            ImagePath = "images/flags/",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("a103d91f-c31e-4d4e-a90f-fe2de03f08d0"),
                            ImagePath = "images/flags/",
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = new Guid("f473b9d1-aa2c-427e-bc95-245b3108c0be"),
                            ImagePath = "images/flags/",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("3eacea80-41db-4ccd-9ecf-7a4610d0bfc1"),
                            ImagePath = "images/flags/",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("ec55154f-656d-4a1d-bd98-8de616570ea1"),
                            ImagePath = "images/flags/",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("0bfb445a-879c-4a6f-b138-857d8a5745d1"),
                            ImagePath = "images/flags/",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("d0e7ae43-5b45-4220-9036-6f030943faf9"),
                            ImagePath = "images/flags/",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("c5fe1053-9a7f-4dce-a18b-364afee2f5de"),
                            ImagePath = "images/flags/",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("0a745341-d82d-43a4-a6f3-09252694aaf7"),
                            ImagePath = "images/flags/",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("150f5f8a-cd01-435c-8cf2-723e18f3bd10"),
                            ImagePath = "images/flags/",
                            Name = "St. Kitts & Nevis"
                        },
                        new
                        {
                            Id = new Guid("07ee9280-69ba-4142-a263-35d20e3161d1"),
                            ImagePath = "images/flags/",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("ba17c9d1-8dc5-46fa-a88b-8c28db1380ed"),
                            ImagePath = "images/flags/",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("b964b7d1-5449-4015-a576-effb92367ceb"),
                            ImagePath = "images/flags/",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("13a22fad-69ab-4f3f-b428-fafd7e261a84"),
                            ImagePath = "images/flags/",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("f44d3041-ac29-424c-84e5-4aa2a695e3d6"),
                            ImagePath = "images/flags/",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("dfc255f1-8bc3-48e2-8cab-5cc0d9cc7e14"),
                            ImagePath = "images/flags/",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("36f49998-c975-4a20-9b10-10f31ff163c5"),
                            ImagePath = "images/flags/",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("ac152e79-3387-4944-b741-2db9a047ee4a"),
                            ImagePath = "images/flags/",
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = new Guid("614353d6-65e9-4d00-89d1-223db9cd1d74"),
                            ImagePath = "images/flags/",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("28f70330-06c0-4145-819c-0cdbf2154e73"),
                            ImagePath = "images/flags/",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("a387f335-32aa-4d67-a085-07e7e89d2f9f"),
                            ImagePath = "images/flags/",
                            Name = "UAE"
                        },
                        new
                        {
                            Id = new Guid("2861d9eb-af3b-4b2b-a1e9-457928cbd382"),
                            ImagePath = "images/flags/",
                            Name = "UK"
                        },
                        new
                        {
                            Id = new Guid("dd433e87-685e-4330-bfa7-33450c0bc56d"),
                            ImagePath = "images/flags/",
                            Name = "USA"
                        },
                        new
                        {
                            Id = new Guid("62431615-841e-4c4d-a6c7-8d26ed889210"),
                            ImagePath = "images/flags/",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("3ab0fb8d-ec84-4459-bc8e-d456e65fe307"),
                            ImagePath = "images/flags/",
                            Name = "Vietnam"
                        });
                });

            modelBuilder.Entity("foodtopia.Models.HeartedRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HeartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId", "RecipeId")
                        .IsUnique();

                    b.ToTable("HeartedRecipes");
                });

            modelBuilder.Entity("foodtopia.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("foodtopia.Models.Instruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("foodtopia.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DifficultyRating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TasteRating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CountryDetailsId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DifficultyAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("DifficultyReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("HeartCount")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TasteAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("TasteReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryDetailsId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("foodtopia.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("character varying(28)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"Username\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("foodtopia.Models.HeartedRecipe", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("HeartedByUsers")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("HeartedRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Ingredient", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodtopia.Models.Instruction", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodtopia.Models.Rating", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.HasOne("foodtopia.Models.Country", "CountryDetails")
                        .WithMany("Recipes")
                        .HasForeignKey("CountryDetailsId");

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryDetails");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Country", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.Navigation("HeartedByUsers");

                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("foodtopia.Models.User", b =>
                {
                    b.Navigation("HeartedRecipes");

                    b.Navigation("Ratings");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
