// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using foodtopia.Database;

#nullable disable

namespace foodtopia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241202023545_CountrySeedComplete")]
    partial class CountrySeedComplete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("foodtopia.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4363ecd6-3cd5-4c45-ba71-5e451e625f60"),
                            ImagePath = "images/flags/afghanistan.svg",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("ee808abe-b721-4139-a7c1-c7a765b4168b"),
                            ImagePath = "images/flags/albania.svg",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("3ed10f2c-e078-482d-af82-41a16fa28101"),
                            ImagePath = "images/flags/algeria.svg",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("7971327f-8d93-44df-90d1-fedf7791e77d"),
                            ImagePath = "images/flags/andorra.svg",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("e1ccedff-f38f-4ba0-9a17-e969b12be8ea"),
                            ImagePath = "images/flags/angola.svg",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("2c9b1c07-3327-4e4a-aa93-b59da6eb6c38"),
                            ImagePath = "images/flags/antigua_barbuda.svg",
                            Name = "Antigua & Barbuda"
                        },
                        new
                        {
                            Id = new Guid("9a1de6ae-921d-4dea-bf5e-28a604f986cb"),
                            ImagePath = "images/flags/argentina.svg",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("17971576-7e5d-4ee5-8aa7-1a630e39f7fa"),
                            ImagePath = "images/flags/armenia.svg",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("c7877889-3c85-4609-9f18-f3ecc9e51ed5"),
                            ImagePath = "images/flags/australia.svg",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("88a8881f-b4c5-4d2f-bd25-053f0b2373c9"),
                            ImagePath = "images/flags/austria.svg",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("8d6b0a3b-7b09-4724-a00b-e3ca0ba58662"),
                            ImagePath = "images/flags/azerbaijan.svg",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("9ffb905d-8aa5-4930-b039-b42912ff429f"),
                            ImagePath = "images/flags/bahamas.svg",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("ba6c10a3-ceeb-462f-bc87-cf80992ae69d"),
                            ImagePath = "images/flags/belgium.svg",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("e64b7aa5-9599-4d4e-845e-5dc67b72343f"),
                            ImagePath = "images/flags/bolivia.svg",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("34b90489-5356-4ecc-a645-c78068d8440f"),
                            ImagePath = "images/flags/brazil.svg",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("b9e6c491-3118-4daf-b80c-379e69cb9729"),
                            ImagePath = "images/flags/cameroon.svg",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("f47c5a8c-6f98-4406-9e09-438cc3774f14"),
                            ImagePath = "images/flags/canada.svg",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("83c298a0-e3bf-424e-9dc2-dbcad98fc9ab"),
                            ImagePath = "images/flags/chile.svg",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("398fe826-bd67-45dc-b28f-a3aafd7627c3"),
                            ImagePath = "images/flags/china.svg",
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("8633df51-74e7-440c-95fb-fd5689304cca"),
                            ImagePath = "images/flags/colombia.svg",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("484e0fc9-0dd0-4b02-942a-5f857b58cec4"),
                            ImagePath = "images/flags/costa_rica.svg",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("deb7f79d-acbb-49e6-a311-0411308ccb4b"),
                            ImagePath = "images/flags/croatia.svg",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("a6cb8885-d266-4526-be0b-ab68e67fceb2"),
                            ImagePath = "images/flags/cuba.svg",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("2ebbe1df-7d16-4288-ad74-a12dc9634582"),
                            ImagePath = "images/flags/denmark.svg",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("f78425e9-a52f-47fd-8af5-75aef3d8a174"),
                            ImagePath = "images/flags/dominican_republic.svg",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("4c2bae94-b941-4b30-8a3f-a1740eb9c1d3"),
                            ImagePath = "images/flags/ecuador.svg",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("4427039b-e399-4da8-9ffb-132fa6e11616"),
                            ImagePath = "images/flags/egypt.svg",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("d81153ba-804d-435f-a6f2-c06f1f55af10"),
                            ImagePath = "images/flags/el_salvador.svg",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("82a4539b-42cd-4054-9c36-42e7aa3871c8"),
                            ImagePath = "images/flags/fiji.svg",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("548e504f-11d6-42a8-bd9b-1cbbaaa8da84"),
                            ImagePath = "images/flags/finland.svg",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("e82f1b48-9ca0-4572-9dec-dee728789991"),
                            ImagePath = "images/flags/france.svg",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("587e244b-ff40-43e2-88af-c00ab3d084a1"),
                            ImagePath = "images/flags/germany.svg",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("1379cce1-ad03-4946-b910-da559b1034c9"),
                            ImagePath = "images/flags/ghana.svg",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("9bed7012-0035-4cd3-8c67-c1377cb8e268"),
                            ImagePath = "images/flags/greece.svg",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("42d98cfd-9f5e-4003-859d-71f4489bf919"),
                            ImagePath = "images/flags/guatemala.svg",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("a3ddfaae-3418-4132-a5a8-2530c95b9323"),
                            ImagePath = "images/flags/hungary.svg",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("3bb65b21-cc89-4558-bdbd-10feab4dc8d6"),
                            ImagePath = "images/flags/iceland.svg",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("70b316fb-21c9-4915-91bf-8ab0e96224df"),
                            ImagePath = "images/flags/india.svg",
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("f6b70b45-700a-439e-8056-49d7db00248e"),
                            ImagePath = "images/flags/ireland.svg",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("7cec2548-6d4f-4d1d-b54b-3d3e916af964"),
                            ImagePath = "images/flags/israel.svg",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("88a22f90-a3e1-45c2-906e-eaeb02ba4345"),
                            ImagePath = "images/flags/italy.svg",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("9bfaf335-873e-4d7e-a874-7301e4b70122"),
                            ImagePath = "images/flags/jamaica.svg",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("2739aa14-5c53-4506-b4f7-34f47620609d"),
                            ImagePath = "images/flags/japan.svg",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("30260711-8836-433e-be4c-58081cb207e5"),
                            ImagePath = "images/flags/kosovo.svg",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("6f82c84c-a778-44f0-b33b-5f806ad2394c"),
                            ImagePath = "images/flags/kuwait.svg",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("bad3b103-91b9-46c0-9051-4f5764376f15"),
                            ImagePath = "images/flags/mexico.svg",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("a7240535-b698-4e01-a31c-a0fca12077ac"),
                            ImagePath = "images/flags/monaco.svg",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("b3185563-c611-4ef5-abd7-e9f25a9dae2a"),
                            ImagePath = "images/flags/morocco.svg",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("581aabb1-e244-49ec-acb0-14c2a4a05fab"),
                            ImagePath = "images/flags/netherlands.svg",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("c8160b03-0bf1-47f5-9069-3b8dc9e139a6"),
                            ImagePath = "images/flags/nigeria.svg",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("a6d04c7c-c5cd-4d2b-a0b5-645c75461ef3"),
                            ImagePath = "images/flags/norway.svg",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("d1c91e36-c9bb-485b-bb31-5b16d0f25857"),
                            ImagePath = "images/flags/pakistan.svg",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("b7dc7991-074a-4bf3-b193-613024fac646"),
                            ImagePath = "images/flags/palestine.svg",
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = new Guid("44d4d424-6a18-4039-a4a6-1ee811253927"),
                            ImagePath = "images/flags/panama.svg",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("b8bfefe5-b1ea-4eec-b092-68662d294b2c"),
                            ImagePath = "images/flags/peru.svg",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("9eeabcf1-36ad-4cd9-b423-77d4ab13cb5e"),
                            ImagePath = "images/flags/philippines.svg",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("b4fb7e9e-d5da-4bb1-8ad2-bbe3e98d3fcb"),
                            ImagePath = "images/flags/poland.svg",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("70316ee1-cd27-4a7e-a66e-bb5f4144b4cd"),
                            ImagePath = "images/flags/portugal.svg",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("9e3d9137-92e3-48a4-9585-f7dbe8010756"),
                            ImagePath = "images/flags/qatar.svg",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("4de723ee-cda8-4b9e-9b52-5c5333109cad"),
                            ImagePath = "images/flags/russia.svg",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("e72352d6-84d7-4ead-81ec-ba418d5e7033"),
                            ImagePath = "images/flags/saudi_arabia.svg",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("3f7ea33e-cb0b-496a-91a4-74f34d06f0b5"),
                            ImagePath = "images/flags/serbia.svg",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("4cc7b5e5-41df-4f17-9d66-dbcf5ef41426"),
                            ImagePath = "images/flags/south_africa.svg",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("22f952a0-8bc7-469d-b1da-1477f08438eb"),
                            ImagePath = "images/flags/south_korea.svg",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("a8983c75-a36b-4279-8518-29fa294b72b2"),
                            ImagePath = "images/flags/spain.svg",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("8486cbeb-9de7-457d-aabb-96a4958e59c7"),
                            ImagePath = "images/flags/sweden.svg",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("b6aadea5-ba3d-4571-8f9f-cc64a3d413c6"),
                            ImagePath = "images/flags/thailand.svg",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("e06b3856-143d-4204-a8c6-7a4531eaf1be"),
                            ImagePath = "images/flags/trinidad&tobago.svg",
                            Name = "Trinidad & Tobago"
                        },
                        new
                        {
                            Id = new Guid("7ebb5278-8282-4538-bc41-0554721484b9"),
                            ImagePath = "images/flags/turkey.svg",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("5f79b196-aec8-4fce-8b7a-b07dfce76e89"),
                            ImagePath = "images/flags/ukraine.svg",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("3df6c61e-ace2-438f-bbce-33f2131131cb"),
                            ImagePath = "images/flags/uae.svg",
                            Name = "UAE"
                        },
                        new
                        {
                            Id = new Guid("3412127f-88c2-44bc-a645-c11632aaadcb"),
                            ImagePath = "images/flags/uk.svg",
                            Name = "UK"
                        },
                        new
                        {
                            Id = new Guid("555f29b6-afb5-4527-8baa-4280ce135b76"),
                            ImagePath = "images/flags/usa.svg",
                            Name = "USA"
                        },
                        new
                        {
                            Id = new Guid("a602059d-13c6-402f-a0cb-a1eaa55d7a73"),
                            ImagePath = "images/flags/venezuela.svg",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("dafb48bf-efa5-4480-9bd9-630e3e4059f1"),
                            ImagePath = "images/flags/vietnam.svg",
                            Name = "Vietnam"
                        });
                });

            modelBuilder.Entity("foodtopia.Models.HeartedRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HeartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId", "RecipeId")
                        .IsUnique();

                    b.ToTable("HeartedRecipes");
                });

            modelBuilder.Entity("foodtopia.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("foodtopia.Models.Instruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Instructions");
                });

            modelBuilder.Entity("foodtopia.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DifficultyRating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TasteRating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CountryDetailsId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DifficultyAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("DifficultyReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("HeartCount")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TasteAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("TasteReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryDetailsId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("foodtopia.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("character varying(28)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"Username\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("foodtopia.Models.HeartedRecipe", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("HeartedByUsers")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("HeartedRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Ingredient", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodtopia.Models.Instruction", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodtopia.Models.Rating", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.HasOne("foodtopia.Models.Country", "CountryDetails")
                        .WithMany("Recipes")
                        .HasForeignKey("CountryDetailsId");

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryDetails");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Country", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.Navigation("HeartedByUsers");

                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("foodtopia.Models.User", b =>
                {
                    b.Navigation("HeartedRecipes");

                    b.Navigation("Ratings");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
