// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using foodtopia.Database;

#nullable disable

namespace foodtopia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250113033301_GuidIdsSeedManualToPassNewDotnet9ExceptionError")]
    partial class GuidIdsSeedManualToPassNewDotnet9ExceptionError
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("foodtopia.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4bc794b1-5000-4dfd-9c9e-451d032744c8"),
                            ImagePath = "images/flags/afghanistan.svg",
                            Name = "Afghanistan",
                            Slug = "afghanistan"
                        },
                        new
                        {
                            Id = new Guid("ff8f1db8-8536-4396-90f9-4842ab99e4bc"),
                            ImagePath = "images/flags/albania.svg",
                            Name = "Albania",
                            Slug = "albania"
                        },
                        new
                        {
                            Id = new Guid("6bdb128a-8c6c-4aba-8103-815ccc37ab3a"),
                            ImagePath = "images/flags/algeria.svg",
                            Name = "Algeria",
                            Slug = "algeria"
                        },
                        new
                        {
                            Id = new Guid("ed13d446-9af2-44ef-9b9e-0e87c11c70ba"),
                            ImagePath = "images/flags/andorra.svg",
                            Name = "Andorra",
                            Slug = "andorra"
                        },
                        new
                        {
                            Id = new Guid("b21f42b5-42b1-4f2e-98c4-714c29288f01"),
                            ImagePath = "images/flags/angola.svg",
                            Name = "Angola",
                            Slug = "angola"
                        },
                        new
                        {
                            Id = new Guid("fb93df64-04c7-4f02-9456-017c0d802b0e"),
                            ImagePath = "images/flags/antigua_barbuda.svg",
                            Name = "Antigua & Barbuda",
                            Slug = "antigua-and-barbuda"
                        },
                        new
                        {
                            Id = new Guid("7ff86fe8-b9b6-485d-a244-59bfb9840160"),
                            ImagePath = "images/flags/argentina.svg",
                            Name = "Argentina",
                            Slug = "argentina"
                        },
                        new
                        {
                            Id = new Guid("ef4fbacb-619d-4b8c-96db-eb68ca6116ae"),
                            ImagePath = "images/flags/armenia.svg",
                            Name = "Armenia",
                            Slug = "armenia"
                        },
                        new
                        {
                            Id = new Guid("1d5d4476-a20d-4160-b009-2a7f2565e0c2"),
                            ImagePath = "images/flags/australia.svg",
                            Name = "Australia",
                            Slug = "australia"
                        },
                        new
                        {
                            Id = new Guid("9439fe2d-211a-4901-9e85-57392790b5cf"),
                            ImagePath = "images/flags/austria.svg",
                            Name = "Austria",
                            Slug = "austria"
                        },
                        new
                        {
                            Id = new Guid("96fb7dd8-17f1-40fc-a328-6834b1818304"),
                            ImagePath = "images/flags/azerbaijan.svg",
                            Name = "Azerbaijan",
                            Slug = "azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("9f758b38-4ce1-41ab-809d-a633f1be3aa6"),
                            ImagePath = "images/flags/bahamas.svg",
                            Name = "Bahamas",
                            Slug = "bahamas"
                        },
                        new
                        {
                            Id = new Guid("71253609-c9b9-4035-ba34-bbf90646f31e"),
                            ImagePath = "images/flags/belgium.svg",
                            Name = "Belgium",
                            Slug = "belgium"
                        },
                        new
                        {
                            Id = new Guid("162452b8-5284-45ff-9001-ecd336021bec"),
                            ImagePath = "images/flags/bolivia.svg",
                            Name = "Bolivia",
                            Slug = "bolivia"
                        },
                        new
                        {
                            Id = new Guid("64c7e557-7a14-454b-97c5-bbcf4cb274dd"),
                            ImagePath = "images/flags/brazil.svg",
                            Name = "Brazil",
                            Slug = "brazil"
                        },
                        new
                        {
                            Id = new Guid("a3a11f10-7372-4049-b791-4db177779ff5"),
                            ImagePath = "images/flags/cameroon.svg",
                            Name = "Cameroon",
                            Slug = "cameroon"
                        },
                        new
                        {
                            Id = new Guid("de5c696e-94f2-4516-a902-8015ad3007a1"),
                            ImagePath = "images/flags/canada.svg",
                            Name = "Canada",
                            Slug = "canada"
                        },
                        new
                        {
                            Id = new Guid("f9e82082-7640-420c-8447-a09433a3bd00"),
                            ImagePath = "images/flags/chile.svg",
                            Name = "Chile",
                            Slug = "chile"
                        },
                        new
                        {
                            Id = new Guid("e5336ea0-d112-4058-8360-de0ec32def0d"),
                            ImagePath = "images/flags/china.svg",
                            Name = "China",
                            Slug = "china"
                        },
                        new
                        {
                            Id = new Guid("846d9792-33d6-42f9-aa56-a2ede3edf63b"),
                            ImagePath = "images/flags/colombia.svg",
                            Name = "Colombia",
                            Slug = "colombia"
                        },
                        new
                        {
                            Id = new Guid("71b7005d-0add-467b-b12f-8ecc8607e889"),
                            ImagePath = "images/flags/costa_rica.svg",
                            Name = "Costa Rica",
                            Slug = "costa-rica"
                        },
                        new
                        {
                            Id = new Guid("2268db96-ce3d-4a95-bf9e-36ba6b03baf3"),
                            ImagePath = "images/flags/croatia.svg",
                            Name = "Croatia",
                            Slug = "croatia"
                        },
                        new
                        {
                            Id = new Guid("ee759b85-8f29-42e7-a785-353f89e690dd"),
                            ImagePath = "images/flags/cuba.svg",
                            Name = "Cuba",
                            Slug = "cuba"
                        },
                        new
                        {
                            Id = new Guid("e9ec5987-63c6-410d-a5a7-3a579d82edac"),
                            ImagePath = "images/flags/denmark.svg",
                            Name = "Denmark",
                            Slug = "denmark"
                        },
                        new
                        {
                            Id = new Guid("3f551bca-b34c-48f0-af2d-05b5929b420b"),
                            ImagePath = "images/flags/dominican_republic.svg",
                            Name = "Dominican Republic",
                            Slug = "dominica-republic"
                        },
                        new
                        {
                            Id = new Guid("1ad8de04-ac42-462d-b8ac-262f3f7870a2"),
                            ImagePath = "images/flags/ecuador.svg",
                            Name = "Ecuador",
                            Slug = "ecuador"
                        },
                        new
                        {
                            Id = new Guid("9dc8871d-c338-4e12-b119-dcef98a5e7fa"),
                            ImagePath = "images/flags/egypt.svg",
                            Name = "Egypt",
                            Slug = "egypt"
                        },
                        new
                        {
                            Id = new Guid("d088946a-b0cc-4616-a07c-19a2c22a7c3f"),
                            ImagePath = "images/flags/el_salvador.svg",
                            Name = "El Salvador",
                            Slug = "el-salvador"
                        },
                        new
                        {
                            Id = new Guid("1b42b510-ad24-4319-89d9-b104127c9f08"),
                            ImagePath = "images/flags/fiji.svg",
                            Name = "Fiji",
                            Slug = "fiji"
                        },
                        new
                        {
                            Id = new Guid("8a65d590-b35d-4445-8544-fc2c70fc3f54"),
                            ImagePath = "images/flags/finland.svg",
                            Name = "Finland",
                            Slug = "finland"
                        },
                        new
                        {
                            Id = new Guid("4c00e5af-921b-427c-962a-8e42fcd7db80"),
                            ImagePath = "images/flags/france.svg",
                            Name = "France",
                            Slug = "france"
                        },
                        new
                        {
                            Id = new Guid("9f4b3a8f-c053-4a14-8053-bca8f4465c33"),
                            ImagePath = "images/flags/germany.svg",
                            Name = "Germany",
                            Slug = "germany"
                        },
                        new
                        {
                            Id = new Guid("eaf84701-b556-4455-9bf5-d6874c2da601"),
                            ImagePath = "images/flags/ghana.svg",
                            Name = "Ghana",
                            Slug = "ghana"
                        },
                        new
                        {
                            Id = new Guid("b6ab2925-6097-48cc-a7f7-d4ed8c2b256a"),
                            ImagePath = "images/flags/greece.svg",
                            Name = "Greece",
                            Slug = "greece"
                        },
                        new
                        {
                            Id = new Guid("e514fbfe-eb2b-4d4e-aa22-a339b668c0ce"),
                            ImagePath = "images/flags/guatemala.svg",
                            Name = "Guatemala",
                            Slug = "guatemala"
                        },
                        new
                        {
                            Id = new Guid("be8e65a3-4281-4146-b391-4d2a132a5eb3"),
                            ImagePath = "images/flags/hungary.svg",
                            Name = "Hungary",
                            Slug = "hungary"
                        },
                        new
                        {
                            Id = new Guid("22d7e231-01a9-45bd-9577-f1ed0fd97448"),
                            ImagePath = "images/flags/iceland.svg",
                            Name = "Iceland",
                            Slug = "iceland"
                        },
                        new
                        {
                            Id = new Guid("f4eaf144-7d25-451f-886b-13805e41c0cf"),
                            ImagePath = "images/flags/india.svg",
                            Name = "India",
                            Slug = "india"
                        },
                        new
                        {
                            Id = new Guid("689dcce4-f72b-4af0-9e48-f2961612a37c"),
                            ImagePath = "images/flags/ireland.svg",
                            Name = "Ireland",
                            Slug = "ireland"
                        },
                        new
                        {
                            Id = new Guid("353cf522-3deb-4bbb-b77d-ad247ab09eba"),
                            ImagePath = "images/flags/israel.svg",
                            Name = "Israel",
                            Slug = "israel"
                        },
                        new
                        {
                            Id = new Guid("683b1e50-3f82-4310-93e5-00398707469f"),
                            ImagePath = "images/flags/italy.svg",
                            Name = "Italy",
                            Slug = "italy"
                        },
                        new
                        {
                            Id = new Guid("66fb47e6-62ad-477a-bd36-06179278cef8"),
                            ImagePath = "images/flags/jamaica.svg",
                            Name = "Jamaica",
                            Slug = "jamaica"
                        },
                        new
                        {
                            Id = new Guid("36fa5cc9-e6a9-49cc-98d0-dd3c9aecce6c"),
                            ImagePath = "images/flags/japan.svg",
                            Name = "Japan",
                            Slug = "japan"
                        },
                        new
                        {
                            Id = new Guid("4ccef4c3-d822-483c-bddf-8bd11c55a3df"),
                            ImagePath = "images/flags/kosovo.svg",
                            Name = "Kosovo",
                            Slug = "kosovo"
                        },
                        new
                        {
                            Id = new Guid("e1cb7738-f5a3-4bc5-a0cf-33115a3a2007"),
                            ImagePath = "images/flags/kuwait.svg",
                            Name = "Kuwait",
                            Slug = "kuwait"
                        },
                        new
                        {
                            Id = new Guid("550054a5-1eb7-4468-b693-a1540a5d3131"),
                            ImagePath = "images/flags/mexico.svg",
                            Name = "Mexico",
                            Slug = "mexico"
                        },
                        new
                        {
                            Id = new Guid("ddd3dc5f-8b84-4435-a271-cd5dc2bd6406"),
                            ImagePath = "images/flags/monaco.svg",
                            Name = "Monaco",
                            Slug = "monaco"
                        },
                        new
                        {
                            Id = new Guid("feecd4a1-2a0d-489e-8b1a-efed38f8ce8e"),
                            ImagePath = "images/flags/morocco.svg",
                            Name = "Morocco",
                            Slug = "morocco"
                        },
                        new
                        {
                            Id = new Guid("bdc127b4-8d7e-4fdc-822f-0da96c9aa7ff"),
                            ImagePath = "images/flags/netherlands.svg",
                            Name = "Netherlands",
                            Slug = "netherlands"
                        },
                        new
                        {
                            Id = new Guid("52ca5dd4-843a-4408-a450-de8d6756a62f"),
                            ImagePath = "images/flags/nigeria.svg",
                            Name = "Nigeria",
                            Slug = "nigeria"
                        },
                        new
                        {
                            Id = new Guid("4ff91cd7-c0cb-4e85-8027-d2ee67d20913"),
                            ImagePath = "images/flags/norway.svg",
                            Name = "Norway",
                            Slug = "norway"
                        },
                        new
                        {
                            Id = new Guid("7a5f9ebf-6d8e-4589-bbfb-d22739b1eb2b"),
                            ImagePath = "images/flags/pakistan.svg",
                            Name = "Pakistan",
                            Slug = "pakistan"
                        },
                        new
                        {
                            Id = new Guid("7bcc9997-a600-4246-a86e-36517c82702d"),
                            ImagePath = "images/flags/palestine.svg",
                            Name = "Palestine",
                            Slug = "palestine"
                        },
                        new
                        {
                            Id = new Guid("c8d9ec81-a9a1-4299-ae80-45d6b1e9b012"),
                            ImagePath = "images/flags/panama.svg",
                            Name = "Panama",
                            Slug = "panama"
                        },
                        new
                        {
                            Id = new Guid("ca309321-8afa-468f-8ace-8027b519e2dc"),
                            ImagePath = "images/flags/peru.svg",
                            Name = "Peru",
                            Slug = "peru"
                        },
                        new
                        {
                            Id = new Guid("d2f03586-3ac2-48a5-9745-398584df4dba"),
                            ImagePath = "images/flags/philippines.svg",
                            Name = "Philippines",
                            Slug = "philippines"
                        },
                        new
                        {
                            Id = new Guid("910a64c2-a8ef-42a7-b1b6-c96a08f3332b"),
                            ImagePath = "images/flags/poland.svg",
                            Name = "Poland",
                            Slug = "poland"
                        },
                        new
                        {
                            Id = new Guid("117df930-fe06-461a-8438-e0400ab4dd7d"),
                            ImagePath = "images/flags/portugal.svg",
                            Name = "Portugal",
                            Slug = "portugal"
                        },
                        new
                        {
                            Id = new Guid("d137f377-8c33-4244-9b22-4f94b5336761"),
                            ImagePath = "images/flags/qatar.svg",
                            Name = "Qatar",
                            Slug = "qatar"
                        },
                        new
                        {
                            Id = new Guid("278eaffa-f980-40d2-b014-10c04163c52a"),
                            ImagePath = "images/flags/russia.svg",
                            Name = "Russia",
                            Slug = "russia"
                        },
                        new
                        {
                            Id = new Guid("4bbe3f9a-c384-4b9d-9cf7-c40c849aca45"),
                            ImagePath = "images/flags/saudi_arabia.svg",
                            Name = "Saudi Arabia",
                            Slug = "saudi-arabia"
                        },
                        new
                        {
                            Id = new Guid("1f5bebf3-8bde-4af8-b845-b340015a573d"),
                            ImagePath = "images/flags/serbia.svg",
                            Name = "Serbia",
                            Slug = "serbia"
                        },
                        new
                        {
                            Id = new Guid("4b9baef3-b816-49b3-817c-f26abe012942"),
                            ImagePath = "images/flags/south_africa.svg",
                            Name = "South Africa",
                            Slug = "south-africa"
                        },
                        new
                        {
                            Id = new Guid("13e5d348-9fd9-4788-b33a-3ff80fd50ac1"),
                            ImagePath = "images/flags/south_korea.svg",
                            Name = "South Korea",
                            Slug = "south-korea"
                        },
                        new
                        {
                            Id = new Guid("e1c716b5-4bda-47b2-9955-920e263bec73"),
                            ImagePath = "images/flags/spain.svg",
                            Name = "Spain",
                            Slug = "spain"
                        },
                        new
                        {
                            Id = new Guid("3561c49c-ed61-4a3e-85f0-23b9c66f42ee"),
                            ImagePath = "images/flags/sweden.svg",
                            Name = "Sweden",
                            Slug = "sweden"
                        },
                        new
                        {
                            Id = new Guid("93a2792c-5349-4b14-abc2-b4781395c394"),
                            ImagePath = "images/flags/thailand.svg",
                            Name = "Thailand",
                            Slug = "thailand"
                        },
                        new
                        {
                            Id = new Guid("492257fb-340d-4f89-aa3f-9952811826f7"),
                            ImagePath = "images/flags/trinidad&tobago.svg",
                            Name = "Trinidad & Tobago",
                            Slug = "trinidad-and-tobago"
                        },
                        new
                        {
                            Id = new Guid("0898e080-716f-4413-91c4-e9c52c493834"),
                            ImagePath = "images/flags/turkey.svg",
                            Name = "Turkey",
                            Slug = "turkey"
                        },
                        new
                        {
                            Id = new Guid("915b012d-b28a-44dc-b053-f2c6a86c8099"),
                            ImagePath = "images/flags/ukraine.svg",
                            Name = "Ukraine",
                            Slug = "ukraine"
                        },
                        new
                        {
                            Id = new Guid("4e815088-0f45-4e2c-84b6-e878cbe1cbd0"),
                            ImagePath = "images/flags/uae.svg",
                            Name = "UAE",
                            Slug = "united-arab-emirates"
                        },
                        new
                        {
                            Id = new Guid("05472a5f-5c4c-4afc-bed2-d60a5b668823"),
                            ImagePath = "images/flags/uk.svg",
                            Name = "UK",
                            Slug = "united-kingdom"
                        },
                        new
                        {
                            Id = new Guid("fc61634e-ea99-43d5-9657-26745fc53530"),
                            ImagePath = "images/flags/usa.svg",
                            Name = "USA",
                            Slug = "usa"
                        },
                        new
                        {
                            Id = new Guid("7ea1a850-1fed-48cd-9baa-24355f5b88fc"),
                            ImagePath = "images/flags/venezuela.svg",
                            Name = "Venezuela",
                            Slug = "venezuela"
                        },
                        new
                        {
                            Id = new Guid("6b600158-b511-44bd-8a52-d4c88a78a1ca"),
                            ImagePath = "images/flags/vietnam.svg",
                            Name = "Vietnam",
                            Slug = "vietnam"
                        });
                });

            modelBuilder.Entity("foodtopia.Models.HeartedRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HeartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId", "RecipeId")
                        .IsUnique();

                    b.ToTable("HeartedRecipes");
                });

            modelBuilder.Entity("foodtopia.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Measurement")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("697e9870-e247-411e-96f3-e56b8d21be1b"),
                            Measurement = "cups",
                            Name = "Flour",
                            Quantity = 2m,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8")
                        },
                        new
                        {
                            Id = new Guid("be8b28cc-b3ba-4d35-866e-5d4ce096a788"),
                            Measurement = "",
                            Name = "Egg",
                            Quantity = 2m,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8")
                        },
                        new
                        {
                            Id = new Guid("f639974d-9bf6-4efd-954c-5abec793ac11"),
                            Measurement = "cup",
                            Name = "Sauce",
                            Quantity = 1m,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8")
                        });
                });

            modelBuilder.Entity("foodtopia.Models.Instruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1d3bbaf-1132-4111-b558-2e027fab8926"),
                            Order = 1,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Crack eggs and add to mixing bowl."
                        },
                        new
                        {
                            Id = new Guid("7cc01c97-66e0-40e3-9e0b-67cb7e5bba8c"),
                            Order = 2,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Whisk until eggs form into a foam-like white texture."
                        },
                        new
                        {
                            Id = new Guid("dbb31e0c-0758-40a2-a7fb-d7e2499befa0"),
                            Order = 3,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Add arrowroot starch to mixing bowl and other spices of your choosing."
                        },
                        new
                        {
                            Id = new Guid("19e6a008-bc94-4bff-8fd7-8b633712f9b9"),
                            Order = 4,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Place inside the over that has been preheated to 350 degrees Fahrenheit for 8-10 minutes."
                        },
                        new
                        {
                            Id = new Guid("e662eb34-f212-424e-a5c5-186954c01f4a"),
                            Order = 5,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Layer the sauce, then the cheese and lastly the toppings."
                        },
                        new
                        {
                            Id = new Guid("bc6b146f-9f96-4e1f-8cc0-26b139d5ef1a"),
                            Order = 6,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Place back into the over for 12-15 minutes."
                        },
                        new
                        {
                            Id = new Guid("53c53fa8-b7c7-47aa-8bd4-6880cee51f01"),
                            Order = 7,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Let the pizza cool for at least 5 minutes and enjoy!"
                        });
                });

            modelBuilder.Entity("foodtopia.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DifficultyRating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TasteRating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DifficultyAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("DifficultyReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TasteAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("TasteReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            CountryId = new Guid("fc61634e-ea99-43d5-9657-26745fc53530"),
                            DifficultyAverage = 0m,
                            DifficultyReviewCount = 0,
                            ImageUrl = "images/recipes/low_calorie_pizza.jpg",
                            Name = "Low calorie pizza",
                            PublishedAt = new DateTime(2025, 1, 13, 3, 33, 1, 141, DateTimeKind.Utc).AddTicks(3940),
                            TasteAverage = 0m,
                            TasteReviewCount = 0
                        });
                });

            modelBuilder.Entity("foodtopia.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("character varying(28)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"Username\" IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Email = "deleted@placeholder.com",
                            FirstName = "Deleted",
                            IsDeleted = true,
                            LastName = "Deleted",
                            Password = "deleted",
                            Role = "none",
                            Username = "deleted"
                        });
                });

            modelBuilder.Entity("foodtopia.Models.HeartedRecipe", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("HeartedByUsers")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("HeartedRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Ingredient", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodtopia.Models.Instruction", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodtopia.Models.Rating", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.HasOne("foodtopia.Models.Country", "Country")
                        .WithMany("Recipes")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Country", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.Navigation("HeartedByUsers");

                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("foodtopia.Models.User", b =>
                {
                    b.Navigation("HeartedRecipes");

                    b.Navigation("Ratings");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
