// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using foodtopia.Database;

#nullable disable

namespace foodtopia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250109145634_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("foodtopia.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8249285d-6244-4de6-a79a-55ca989bed88"),
                            ImagePath = "images/flags/afghanistan.svg",
                            Name = "Afghanistan",
                            Slug = "afghanistan"
                        },
                        new
                        {
                            Id = new Guid("4ffd1636-b9c1-47aa-b20e-0d02a5182348"),
                            ImagePath = "images/flags/albania.svg",
                            Name = "Albania",
                            Slug = "albania"
                        },
                        new
                        {
                            Id = new Guid("038605c3-9499-4205-a0ac-f71ef43b47b3"),
                            ImagePath = "images/flags/algeria.svg",
                            Name = "Algeria",
                            Slug = "algeria"
                        },
                        new
                        {
                            Id = new Guid("f79788fc-c9a9-4f15-9ea3-ce375205d15c"),
                            ImagePath = "images/flags/andorra.svg",
                            Name = "Andorra",
                            Slug = "andorra"
                        },
                        new
                        {
                            Id = new Guid("902d5369-17e0-45b9-9367-9ced0cedeb6c"),
                            ImagePath = "images/flags/angola.svg",
                            Name = "Angola",
                            Slug = "angola"
                        },
                        new
                        {
                            Id = new Guid("beeb07ec-a1f2-474f-aaca-67e544db05b3"),
                            ImagePath = "images/flags/antigua_barbuda.svg",
                            Name = "Antigua & Barbuda",
                            Slug = "antigua-and-barbuda"
                        },
                        new
                        {
                            Id = new Guid("9e42a217-8054-4cee-8b7a-087fe95a79f9"),
                            ImagePath = "images/flags/argentina.svg",
                            Name = "Argentina",
                            Slug = "argentina"
                        },
                        new
                        {
                            Id = new Guid("a308e22f-bf3c-4787-97ba-ed2baf1db7ba"),
                            ImagePath = "images/flags/armenia.svg",
                            Name = "Armenia",
                            Slug = "armenia"
                        },
                        new
                        {
                            Id = new Guid("8b8aab18-f234-4919-b233-e27e6485811e"),
                            ImagePath = "images/flags/australia.svg",
                            Name = "Australia",
                            Slug = "australia"
                        },
                        new
                        {
                            Id = new Guid("1dca600a-c5f0-45a9-be79-5e86b8b68f0e"),
                            ImagePath = "images/flags/austria.svg",
                            Name = "Austria",
                            Slug = "austria"
                        },
                        new
                        {
                            Id = new Guid("8bd372dc-061f-4bfa-ae4e-53b726330f1b"),
                            ImagePath = "images/flags/azerbaijan.svg",
                            Name = "Azerbaijan",
                            Slug = "azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("6e12219e-44e5-495a-8fbc-d0f74848014b"),
                            ImagePath = "images/flags/bahamas.svg",
                            Name = "Bahamas",
                            Slug = "bahamas"
                        },
                        new
                        {
                            Id = new Guid("e60e384e-a7cf-411a-9362-76d0aeec619b"),
                            ImagePath = "images/flags/belgium.svg",
                            Name = "Belgium",
                            Slug = "belgium"
                        },
                        new
                        {
                            Id = new Guid("fbbee294-de2d-4f6a-93ab-b6df3853e64a"),
                            ImagePath = "images/flags/bolivia.svg",
                            Name = "Bolivia",
                            Slug = "bolivia"
                        },
                        new
                        {
                            Id = new Guid("962dea70-2f53-4753-8ea4-52cbb31d4175"),
                            ImagePath = "images/flags/brazil.svg",
                            Name = "Brazil",
                            Slug = "brazil"
                        },
                        new
                        {
                            Id = new Guid("597558ac-0f1c-4eeb-8751-71bf881d3d78"),
                            ImagePath = "images/flags/cameroon.svg",
                            Name = "Cameroon",
                            Slug = "cameroon"
                        },
                        new
                        {
                            Id = new Guid("63dee376-5006-44fc-a763-730cd9bbff8a"),
                            ImagePath = "images/flags/canada.svg",
                            Name = "Canada",
                            Slug = "canada"
                        },
                        new
                        {
                            Id = new Guid("31f03777-3e94-402d-b4eb-c7c6e9903108"),
                            ImagePath = "images/flags/chile.svg",
                            Name = "Chile",
                            Slug = "chile"
                        },
                        new
                        {
                            Id = new Guid("59784003-0163-470e-8238-e63c2be3ebb0"),
                            ImagePath = "images/flags/china.svg",
                            Name = "China",
                            Slug = "china"
                        },
                        new
                        {
                            Id = new Guid("1d8a47a1-1130-4ad4-8f4d-4e3c300d89ec"),
                            ImagePath = "images/flags/colombia.svg",
                            Name = "Colombia",
                            Slug = "colombia"
                        },
                        new
                        {
                            Id = new Guid("99e67deb-d8aa-48cf-b011-afc6e37ad21d"),
                            ImagePath = "images/flags/costa_rica.svg",
                            Name = "Costa Rica",
                            Slug = "costa-rica"
                        },
                        new
                        {
                            Id = new Guid("463671c5-fc34-4294-b600-92ced08b4a41"),
                            ImagePath = "images/flags/croatia.svg",
                            Name = "Croatia",
                            Slug = "croatia"
                        },
                        new
                        {
                            Id = new Guid("9b880c26-de06-41b1-8579-e31b7c70ebef"),
                            ImagePath = "images/flags/cuba.svg",
                            Name = "Cuba",
                            Slug = "cuba"
                        },
                        new
                        {
                            Id = new Guid("3a95d925-25cd-4073-bccb-78f58cc3fc4c"),
                            ImagePath = "images/flags/denmark.svg",
                            Name = "Denmark",
                            Slug = "denmark"
                        },
                        new
                        {
                            Id = new Guid("a6ddb27c-0eba-4c64-b926-95a839ce03e8"),
                            ImagePath = "images/flags/dominican_republic.svg",
                            Name = "Dominican Republic",
                            Slug = "dominica-republic"
                        },
                        new
                        {
                            Id = new Guid("f9899140-d549-4c9e-8d05-e12b5ea83623"),
                            ImagePath = "images/flags/ecuador.svg",
                            Name = "Ecuador",
                            Slug = "ecuador"
                        },
                        new
                        {
                            Id = new Guid("c7be5a6f-4a9a-4da4-8910-7e3f9355f3cb"),
                            ImagePath = "images/flags/egypt.svg",
                            Name = "Egypt",
                            Slug = "egypt"
                        },
                        new
                        {
                            Id = new Guid("cf88669c-827f-463a-a6cf-75cb10faa93b"),
                            ImagePath = "images/flags/el_salvador.svg",
                            Name = "El Salvador",
                            Slug = "el-salvador"
                        },
                        new
                        {
                            Id = new Guid("f1269377-754b-437e-b8e2-3c3b26d160d7"),
                            ImagePath = "images/flags/fiji.svg",
                            Name = "Fiji",
                            Slug = "fiji"
                        },
                        new
                        {
                            Id = new Guid("18e8ff81-6234-4aa6-902e-69cefb26aca5"),
                            ImagePath = "images/flags/finland.svg",
                            Name = "Finland",
                            Slug = "finland"
                        },
                        new
                        {
                            Id = new Guid("8ffc8e08-3a94-4da1-a504-1cd3cb08eff5"),
                            ImagePath = "images/flags/france.svg",
                            Name = "France",
                            Slug = "france"
                        },
                        new
                        {
                            Id = new Guid("8c7a2ce6-9f2f-4bdd-83d6-b24801310760"),
                            ImagePath = "images/flags/germany.svg",
                            Name = "Germany",
                            Slug = "germany"
                        },
                        new
                        {
                            Id = new Guid("7b1b2a17-156a-413d-b57e-c49fead48e22"),
                            ImagePath = "images/flags/ghana.svg",
                            Name = "Ghana",
                            Slug = "ghana"
                        },
                        new
                        {
                            Id = new Guid("eb014b54-2b8e-4ce8-ac17-d0b14c60e1ae"),
                            ImagePath = "images/flags/greece.svg",
                            Name = "Greece",
                            Slug = "greece"
                        },
                        new
                        {
                            Id = new Guid("01f4ac5c-11cb-46a3-b455-4c27c05cdca9"),
                            ImagePath = "images/flags/guatemala.svg",
                            Name = "Guatemala",
                            Slug = "guatemala"
                        },
                        new
                        {
                            Id = new Guid("33195fed-3b63-46fb-b49c-15f7caf6ed1c"),
                            ImagePath = "images/flags/hungary.svg",
                            Name = "Hungary",
                            Slug = "hungary"
                        },
                        new
                        {
                            Id = new Guid("9eb0882c-e56c-4a7e-8c03-e1997f1b787e"),
                            ImagePath = "images/flags/iceland.svg",
                            Name = "Iceland",
                            Slug = "iceland"
                        },
                        new
                        {
                            Id = new Guid("732f69b7-13c1-449c-ac71-502bb36512e8"),
                            ImagePath = "images/flags/india.svg",
                            Name = "India",
                            Slug = "india"
                        },
                        new
                        {
                            Id = new Guid("7a6b2878-a943-4d1f-b7ab-458caeb158e8"),
                            ImagePath = "images/flags/ireland.svg",
                            Name = "Ireland",
                            Slug = "ireland"
                        },
                        new
                        {
                            Id = new Guid("48cb1fe1-dc53-4297-ab4c-d83b8515fbe5"),
                            ImagePath = "images/flags/israel.svg",
                            Name = "Israel",
                            Slug = "israel"
                        },
                        new
                        {
                            Id = new Guid("76009c1d-0de7-44e7-a8ca-bd9d6a0a816b"),
                            ImagePath = "images/flags/italy.svg",
                            Name = "Italy",
                            Slug = "italy"
                        },
                        new
                        {
                            Id = new Guid("96b22919-3f04-43b3-a4c2-f9691e523936"),
                            ImagePath = "images/flags/jamaica.svg",
                            Name = "Jamaica",
                            Slug = "jamaica"
                        },
                        new
                        {
                            Id = new Guid("413520ac-6f4b-45df-bd96-5e2aefed0be0"),
                            ImagePath = "images/flags/japan.svg",
                            Name = "Japan",
                            Slug = "japan"
                        },
                        new
                        {
                            Id = new Guid("3ddd41b8-7ba7-4945-9c00-0b496f0953af"),
                            ImagePath = "images/flags/kosovo.svg",
                            Name = "Kosovo",
                            Slug = "kosovo"
                        },
                        new
                        {
                            Id = new Guid("86c98c7f-35f2-44e7-b44c-a2603cfd17c2"),
                            ImagePath = "images/flags/kuwait.svg",
                            Name = "Kuwait",
                            Slug = "kuwait"
                        },
                        new
                        {
                            Id = new Guid("20d93819-4e82-4eee-b56d-20f08d2e0c5b"),
                            ImagePath = "images/flags/mexico.svg",
                            Name = "Mexico",
                            Slug = "mexico"
                        },
                        new
                        {
                            Id = new Guid("8549307c-e92b-4c90-899c-35e67eb02732"),
                            ImagePath = "images/flags/monaco.svg",
                            Name = "Monaco",
                            Slug = "monaco"
                        },
                        new
                        {
                            Id = new Guid("f3e6e63c-a7a0-4090-9326-ccd5e2dc5008"),
                            ImagePath = "images/flags/morocco.svg",
                            Name = "Morocco",
                            Slug = "morocco"
                        },
                        new
                        {
                            Id = new Guid("8ed7b64f-1a56-4d9d-ba35-fd2f83047f1e"),
                            ImagePath = "images/flags/netherlands.svg",
                            Name = "Netherlands",
                            Slug = "netherlands"
                        },
                        new
                        {
                            Id = new Guid("273719f6-22df-400b-99b8-6d499a7a2f9e"),
                            ImagePath = "images/flags/nigeria.svg",
                            Name = "Nigeria",
                            Slug = "nigeria"
                        },
                        new
                        {
                            Id = new Guid("13488b4b-539a-40ca-a40b-bea362bdbd1b"),
                            ImagePath = "images/flags/norway.svg",
                            Name = "Norway",
                            Slug = "norway"
                        },
                        new
                        {
                            Id = new Guid("63a80847-172c-41e9-b35f-40d8c1237ab1"),
                            ImagePath = "images/flags/pakistan.svg",
                            Name = "Pakistan",
                            Slug = "pakistan"
                        },
                        new
                        {
                            Id = new Guid("5456e649-bf0a-4507-b60d-251aa750cc4c"),
                            ImagePath = "images/flags/palestine.svg",
                            Name = "Palestine",
                            Slug = "palestine"
                        },
                        new
                        {
                            Id = new Guid("bf94588a-8cb3-46d9-a17e-5878cdafe268"),
                            ImagePath = "images/flags/panama.svg",
                            Name = "Panama",
                            Slug = "panama"
                        },
                        new
                        {
                            Id = new Guid("65284b4a-374a-4144-9509-3598b4c270fd"),
                            ImagePath = "images/flags/peru.svg",
                            Name = "Peru",
                            Slug = "peru"
                        },
                        new
                        {
                            Id = new Guid("7f8cc654-9cea-46c9-af92-ae1ee272677a"),
                            ImagePath = "images/flags/philippines.svg",
                            Name = "Philippines",
                            Slug = "philippines"
                        },
                        new
                        {
                            Id = new Guid("8ccb0c9f-5ade-4e99-b4e7-9e9809d20682"),
                            ImagePath = "images/flags/poland.svg",
                            Name = "Poland",
                            Slug = "poland"
                        },
                        new
                        {
                            Id = new Guid("802f65b6-6c64-494f-a1eb-802d5cc594d6"),
                            ImagePath = "images/flags/portugal.svg",
                            Name = "Portugal",
                            Slug = "portugal"
                        },
                        new
                        {
                            Id = new Guid("9c738db6-b1b0-4367-8173-30f60b8550fb"),
                            ImagePath = "images/flags/qatar.svg",
                            Name = "Qatar",
                            Slug = "qatar"
                        },
                        new
                        {
                            Id = new Guid("d37b096d-86dc-4deb-ba2a-ed067b1d3cc2"),
                            ImagePath = "images/flags/russia.svg",
                            Name = "Russia",
                            Slug = "russia"
                        },
                        new
                        {
                            Id = new Guid("16ddc3e7-9748-477e-b7c0-8d503b992e2e"),
                            ImagePath = "images/flags/saudi_arabia.svg",
                            Name = "Saudi Arabia",
                            Slug = "saudi-arabia"
                        },
                        new
                        {
                            Id = new Guid("86e7903b-1f81-4534-8f6a-1cb6b7ad5782"),
                            ImagePath = "images/flags/serbia.svg",
                            Name = "Serbia",
                            Slug = "serbia"
                        },
                        new
                        {
                            Id = new Guid("c3dbc242-ab34-4c47-9707-a2195187915e"),
                            ImagePath = "images/flags/south_africa.svg",
                            Name = "South Africa",
                            Slug = "south-africa"
                        },
                        new
                        {
                            Id = new Guid("a05f52e8-51f7-4626-8329-feb7f5cb5249"),
                            ImagePath = "images/flags/south_korea.svg",
                            Name = "South Korea",
                            Slug = "south-korea"
                        },
                        new
                        {
                            Id = new Guid("dfe7829b-4d19-4db5-ae73-d896709e3d33"),
                            ImagePath = "images/flags/spain.svg",
                            Name = "Spain",
                            Slug = "spain"
                        },
                        new
                        {
                            Id = new Guid("f30dd8f5-4c4a-4eb4-b28d-0e559b1dea75"),
                            ImagePath = "images/flags/sweden.svg",
                            Name = "Sweden",
                            Slug = "sweden"
                        },
                        new
                        {
                            Id = new Guid("b61f5b0d-a6b5-4189-9af2-3752028727ed"),
                            ImagePath = "images/flags/thailand.svg",
                            Name = "Thailand",
                            Slug = "thailand"
                        },
                        new
                        {
                            Id = new Guid("c28bd523-8245-46bf-83fa-8c1e95a764e4"),
                            ImagePath = "images/flags/trinidad&tobago.svg",
                            Name = "Trinidad & Tobago",
                            Slug = "trinidad-and-tobago"
                        },
                        new
                        {
                            Id = new Guid("77bce5a9-8530-4a4c-92bf-1b922efaf625"),
                            ImagePath = "images/flags/turkey.svg",
                            Name = "Turkey",
                            Slug = "turkey"
                        },
                        new
                        {
                            Id = new Guid("2ca071fb-0cd8-4962-b85c-7342f9353e43"),
                            ImagePath = "images/flags/ukraine.svg",
                            Name = "Ukraine",
                            Slug = "ukraine"
                        },
                        new
                        {
                            Id = new Guid("da874b21-e67c-4560-993b-e61c4ea282fd"),
                            ImagePath = "images/flags/uae.svg",
                            Name = "UAE",
                            Slug = "united-arab-emirates"
                        },
                        new
                        {
                            Id = new Guid("0a34bbde-21c7-4746-8714-721a0c0597b3"),
                            ImagePath = "images/flags/uk.svg",
                            Name = "UK",
                            Slug = "united-kingdom"
                        },
                        new
                        {
                            Id = new Guid("fc61634e-ea99-43d5-9657-26745fc53530"),
                            ImagePath = "images/flags/usa.svg",
                            Name = "USA",
                            Slug = "usa"
                        },
                        new
                        {
                            Id = new Guid("779f2d29-d9da-46d8-a78f-e6ca5a393a5b"),
                            ImagePath = "images/flags/venezuela.svg",
                            Name = "Venezuela",
                            Slug = "venezuela"
                        },
                        new
                        {
                            Id = new Guid("00d039ac-65ba-4c88-8776-e66d80aeda59"),
                            ImagePath = "images/flags/vietnam.svg",
                            Name = "Vietnam",
                            Slug = "vietnam"
                        });
                });

            modelBuilder.Entity("foodtopia.Models.HeartedRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HeartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId", "RecipeId")
                        .IsUnique();

                    b.ToTable("HeartedRecipes");
                });

            modelBuilder.Entity("foodtopia.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Measurement")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("624aaf79-8a0a-4e07-b7ae-3228ac6b8bd9"),
                            Measurement = "cups",
                            Name = "Flour",
                            Quantity = 2m,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8")
                        },
                        new
                        {
                            Id = new Guid("e393ee0f-750e-4073-b3d9-e63bf19ab5fe"),
                            Measurement = "",
                            Name = "Egg",
                            Quantity = 2m,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8")
                        },
                        new
                        {
                            Id = new Guid("d3d4f946-ad13-4c2b-960e-9cea2cc38329"),
                            Measurement = "cup",
                            Name = "Sauce",
                            Quantity = 1m,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8")
                        });
                });

            modelBuilder.Entity("foodtopia.Models.Instruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60c30f84-d112-4c80-9837-e97600a43434"),
                            Order = 1,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Crack eggs and add to mixing bowl."
                        },
                        new
                        {
                            Id = new Guid("5051f18a-8618-4beb-b97b-e8e624ab2200"),
                            Order = 2,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Whisk until eggs form into a foam-like white texture."
                        },
                        new
                        {
                            Id = new Guid("95a60176-994b-42f7-a5e0-10dafa06da2f"),
                            Order = 3,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Add arrowroot starch to mixing bowl and other spices of your choosing."
                        },
                        new
                        {
                            Id = new Guid("b4308569-9e4e-43c4-b211-329eadf3e62b"),
                            Order = 4,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Place inside the over that has been preheated to 350 degrees Fahrenheit for 8-10 minutes."
                        },
                        new
                        {
                            Id = new Guid("ee9d51cd-6663-4fe0-8219-c4aa83967adc"),
                            Order = 5,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Layer the sauce, then the cheese and lastly the toppings."
                        },
                        new
                        {
                            Id = new Guid("d0468a9c-b3ef-42f8-823a-6fb4adb003ec"),
                            Order = 6,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Place back into the over for 12-15 minutes."
                        },
                        new
                        {
                            Id = new Guid("e45c3910-4120-4c3f-a73c-9fd7841ffbab"),
                            Order = 7,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Let the pizza cool for at least 5 minutes and enjoy!"
                        });
                });

            modelBuilder.Entity("foodtopia.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DifficultyRating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TasteRating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DifficultyAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("DifficultyReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("HeartCount")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TasteAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("TasteReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            CountryId = new Guid("fc61634e-ea99-43d5-9657-26745fc53530"),
                            DifficultyAverage = 0m,
                            DifficultyReviewCount = 0,
                            HeartCount = 0,
                            ImageUrl = "images/recipes/low_calorie_pizza.jpg",
                            Name = "Low calorie pizza",
                            PublishedAt = new DateTime(2025, 1, 9, 14, 56, 34, 295, DateTimeKind.Utc).AddTicks(6180),
                            TasteAverage = 0m,
                            TasteReviewCount = 0
                        });
                });

            modelBuilder.Entity("foodtopia.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("character varying(28)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"Username\" IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Email = "deleted@placeholder.com",
                            FirstName = "Deleted",
                            IsDeleted = true,
                            LastName = "Deleted",
                            Password = "deleted",
                            Role = "none",
                            Username = "deleted"
                        });
                });

            modelBuilder.Entity("foodtopia.Models.HeartedRecipe", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("HeartedByUsers")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("HeartedRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Ingredient", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodtopia.Models.Instruction", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodtopia.Models.Rating", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.HasOne("foodtopia.Models.Country", "CountryOrigin")
                        .WithMany("Recipes")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CountryOrigin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Country", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.Navigation("HeartedByUsers");

                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("foodtopia.Models.User", b =>
                {
                    b.Navigation("HeartedRecipes");

                    b.Navigation("Ratings");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
