// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using foodtopia.Database;

#nullable disable

namespace foodtopia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250112002614_AddCountryToRecipeRelationship")]
    partial class AddCountryToRecipeRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("foodtopia.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dd4cbc86-d78f-4c2b-878a-a48d7e85b7e6"),
                            ImagePath = "images/flags/afghanistan.svg",
                            Name = "Afghanistan",
                            Slug = "afghanistan"
                        },
                        new
                        {
                            Id = new Guid("596dd9b7-699f-49cd-ab7e-29afae8d97df"),
                            ImagePath = "images/flags/albania.svg",
                            Name = "Albania",
                            Slug = "albania"
                        },
                        new
                        {
                            Id = new Guid("e22a76ba-dcab-4b1b-a892-0d58370022e0"),
                            ImagePath = "images/flags/algeria.svg",
                            Name = "Algeria",
                            Slug = "algeria"
                        },
                        new
                        {
                            Id = new Guid("521b1965-11ea-4218-8fcc-a81794769d3d"),
                            ImagePath = "images/flags/andorra.svg",
                            Name = "Andorra",
                            Slug = "andorra"
                        },
                        new
                        {
                            Id = new Guid("e2cd761b-91e0-47fd-be00-4e99705c87e7"),
                            ImagePath = "images/flags/angola.svg",
                            Name = "Angola",
                            Slug = "angola"
                        },
                        new
                        {
                            Id = new Guid("29ccf4b4-46f8-4b6c-998d-39fbb374f06b"),
                            ImagePath = "images/flags/antigua_barbuda.svg",
                            Name = "Antigua & Barbuda",
                            Slug = "antigua-and-barbuda"
                        },
                        new
                        {
                            Id = new Guid("3032500c-c5c3-463a-9a22-bf82774fe298"),
                            ImagePath = "images/flags/argentina.svg",
                            Name = "Argentina",
                            Slug = "argentina"
                        },
                        new
                        {
                            Id = new Guid("214085d3-f12f-4f4d-8c8e-466af2744516"),
                            ImagePath = "images/flags/armenia.svg",
                            Name = "Armenia",
                            Slug = "armenia"
                        },
                        new
                        {
                            Id = new Guid("1748659f-78ed-4d55-913b-5f086be32871"),
                            ImagePath = "images/flags/australia.svg",
                            Name = "Australia",
                            Slug = "australia"
                        },
                        new
                        {
                            Id = new Guid("2773fb1c-486d-47ca-a162-651f0a0a5ecb"),
                            ImagePath = "images/flags/austria.svg",
                            Name = "Austria",
                            Slug = "austria"
                        },
                        new
                        {
                            Id = new Guid("1c8fc373-77ea-4f2a-b9bc-eecad5c9960d"),
                            ImagePath = "images/flags/azerbaijan.svg",
                            Name = "Azerbaijan",
                            Slug = "azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("24535263-c259-478d-a9a2-43a6e6fc19e2"),
                            ImagePath = "images/flags/bahamas.svg",
                            Name = "Bahamas",
                            Slug = "bahamas"
                        },
                        new
                        {
                            Id = new Guid("3048dd59-ae9d-4566-a557-31fa3b9cbedd"),
                            ImagePath = "images/flags/belgium.svg",
                            Name = "Belgium",
                            Slug = "belgium"
                        },
                        new
                        {
                            Id = new Guid("860052db-1690-4ae7-b419-6fcfebaea268"),
                            ImagePath = "images/flags/bolivia.svg",
                            Name = "Bolivia",
                            Slug = "bolivia"
                        },
                        new
                        {
                            Id = new Guid("536999bb-dc41-431f-be0f-58fb54a3e029"),
                            ImagePath = "images/flags/brazil.svg",
                            Name = "Brazil",
                            Slug = "brazil"
                        },
                        new
                        {
                            Id = new Guid("b1f6f5e5-2694-4ce5-877e-ca2d930dd733"),
                            ImagePath = "images/flags/cameroon.svg",
                            Name = "Cameroon",
                            Slug = "cameroon"
                        },
                        new
                        {
                            Id = new Guid("34867253-ed32-4b19-9e82-982a838a231e"),
                            ImagePath = "images/flags/canada.svg",
                            Name = "Canada",
                            Slug = "canada"
                        },
                        new
                        {
                            Id = new Guid("612806b8-0f89-4202-b385-f9094ed3576c"),
                            ImagePath = "images/flags/chile.svg",
                            Name = "Chile",
                            Slug = "chile"
                        },
                        new
                        {
                            Id = new Guid("8f255e1b-72ff-4557-aca6-a410c6ef28a9"),
                            ImagePath = "images/flags/china.svg",
                            Name = "China",
                            Slug = "china"
                        },
                        new
                        {
                            Id = new Guid("9ed31919-2a90-4a27-90af-c61613d76d08"),
                            ImagePath = "images/flags/colombia.svg",
                            Name = "Colombia",
                            Slug = "colombia"
                        },
                        new
                        {
                            Id = new Guid("df818785-2928-407c-ada0-5150d767eb20"),
                            ImagePath = "images/flags/costa_rica.svg",
                            Name = "Costa Rica",
                            Slug = "costa-rica"
                        },
                        new
                        {
                            Id = new Guid("df68c932-9fa2-4c83-ac96-53c3f7307723"),
                            ImagePath = "images/flags/croatia.svg",
                            Name = "Croatia",
                            Slug = "croatia"
                        },
                        new
                        {
                            Id = new Guid("73bad6da-6063-4cab-8fd9-6c88b610c581"),
                            ImagePath = "images/flags/cuba.svg",
                            Name = "Cuba",
                            Slug = "cuba"
                        },
                        new
                        {
                            Id = new Guid("928ef8dd-0fa6-4869-81b2-bfc707f0fcd0"),
                            ImagePath = "images/flags/denmark.svg",
                            Name = "Denmark",
                            Slug = "denmark"
                        },
                        new
                        {
                            Id = new Guid("20baa712-8026-41a9-ad0b-335ef8b6345f"),
                            ImagePath = "images/flags/dominican_republic.svg",
                            Name = "Dominican Republic",
                            Slug = "dominica-republic"
                        },
                        new
                        {
                            Id = new Guid("dcfbd07f-1370-4f68-a605-26a9cbf845cc"),
                            ImagePath = "images/flags/ecuador.svg",
                            Name = "Ecuador",
                            Slug = "ecuador"
                        },
                        new
                        {
                            Id = new Guid("046b8e9f-4055-4e59-8414-2b675af1b380"),
                            ImagePath = "images/flags/egypt.svg",
                            Name = "Egypt",
                            Slug = "egypt"
                        },
                        new
                        {
                            Id = new Guid("21367964-fb52-408c-96e9-c39f95022354"),
                            ImagePath = "images/flags/el_salvador.svg",
                            Name = "El Salvador",
                            Slug = "el-salvador"
                        },
                        new
                        {
                            Id = new Guid("ba153247-01e0-4ef0-ad10-70bebba17a67"),
                            ImagePath = "images/flags/fiji.svg",
                            Name = "Fiji",
                            Slug = "fiji"
                        },
                        new
                        {
                            Id = new Guid("9e86a69f-58f7-4abf-a5d6-c3461fee8889"),
                            ImagePath = "images/flags/finland.svg",
                            Name = "Finland",
                            Slug = "finland"
                        },
                        new
                        {
                            Id = new Guid("0b1764f9-80da-4cae-b900-4faca3f87b3a"),
                            ImagePath = "images/flags/france.svg",
                            Name = "France",
                            Slug = "france"
                        },
                        new
                        {
                            Id = new Guid("2637d187-5fce-4de9-8179-49e8d5abfb97"),
                            ImagePath = "images/flags/germany.svg",
                            Name = "Germany",
                            Slug = "germany"
                        },
                        new
                        {
                            Id = new Guid("a43532e6-7e4d-4af3-bc04-1272602a971f"),
                            ImagePath = "images/flags/ghana.svg",
                            Name = "Ghana",
                            Slug = "ghana"
                        },
                        new
                        {
                            Id = new Guid("98ddb29a-0a34-4553-baad-dacf1eb06703"),
                            ImagePath = "images/flags/greece.svg",
                            Name = "Greece",
                            Slug = "greece"
                        },
                        new
                        {
                            Id = new Guid("223a2cbc-789c-4524-932c-8089f44724eb"),
                            ImagePath = "images/flags/guatemala.svg",
                            Name = "Guatemala",
                            Slug = "guatemala"
                        },
                        new
                        {
                            Id = new Guid("8995e0a0-418c-4864-996a-b534307ba1c4"),
                            ImagePath = "images/flags/hungary.svg",
                            Name = "Hungary",
                            Slug = "hungary"
                        },
                        new
                        {
                            Id = new Guid("20f71b82-eb8a-4988-b23a-02ca4d7e1e3d"),
                            ImagePath = "images/flags/iceland.svg",
                            Name = "Iceland",
                            Slug = "iceland"
                        },
                        new
                        {
                            Id = new Guid("1c14e1c5-a4d1-43d1-bda7-e2bb0a19ac32"),
                            ImagePath = "images/flags/india.svg",
                            Name = "India",
                            Slug = "india"
                        },
                        new
                        {
                            Id = new Guid("617ced29-4c90-4070-accd-01438fc5168a"),
                            ImagePath = "images/flags/ireland.svg",
                            Name = "Ireland",
                            Slug = "ireland"
                        },
                        new
                        {
                            Id = new Guid("09eafec3-8c30-48bc-9c49-9c146d3f8363"),
                            ImagePath = "images/flags/israel.svg",
                            Name = "Israel",
                            Slug = "israel"
                        },
                        new
                        {
                            Id = new Guid("f8f486fe-c7b9-49b0-9e49-888d62cb3c43"),
                            ImagePath = "images/flags/italy.svg",
                            Name = "Italy",
                            Slug = "italy"
                        },
                        new
                        {
                            Id = new Guid("8058b0d2-f7c8-4f1f-8b49-6f79aa4e6bcf"),
                            ImagePath = "images/flags/jamaica.svg",
                            Name = "Jamaica",
                            Slug = "jamaica"
                        },
                        new
                        {
                            Id = new Guid("da0c9509-1957-488f-9045-2d5fa40764c4"),
                            ImagePath = "images/flags/japan.svg",
                            Name = "Japan",
                            Slug = "japan"
                        },
                        new
                        {
                            Id = new Guid("f7de96ed-44df-4aa3-807b-0d55bd3c0c6c"),
                            ImagePath = "images/flags/kosovo.svg",
                            Name = "Kosovo",
                            Slug = "kosovo"
                        },
                        new
                        {
                            Id = new Guid("c6fc08a4-ea24-4549-812e-9d2a7b6ccf4d"),
                            ImagePath = "images/flags/kuwait.svg",
                            Name = "Kuwait",
                            Slug = "kuwait"
                        },
                        new
                        {
                            Id = new Guid("7409315a-e16e-4a12-8f51-e22a73881e34"),
                            ImagePath = "images/flags/mexico.svg",
                            Name = "Mexico",
                            Slug = "mexico"
                        },
                        new
                        {
                            Id = new Guid("db3d717e-c53a-4b5e-98e6-824ef620de62"),
                            ImagePath = "images/flags/monaco.svg",
                            Name = "Monaco",
                            Slug = "monaco"
                        },
                        new
                        {
                            Id = new Guid("8df92431-576b-4355-9d39-6a7a1de66486"),
                            ImagePath = "images/flags/morocco.svg",
                            Name = "Morocco",
                            Slug = "morocco"
                        },
                        new
                        {
                            Id = new Guid("e1bd80cf-f5a1-4152-b330-431b907467a8"),
                            ImagePath = "images/flags/netherlands.svg",
                            Name = "Netherlands",
                            Slug = "netherlands"
                        },
                        new
                        {
                            Id = new Guid("6b86d383-ec9e-4f79-a854-81269452e488"),
                            ImagePath = "images/flags/nigeria.svg",
                            Name = "Nigeria",
                            Slug = "nigeria"
                        },
                        new
                        {
                            Id = new Guid("0f7409ab-d36c-4696-9a85-9cabea829e5b"),
                            ImagePath = "images/flags/norway.svg",
                            Name = "Norway",
                            Slug = "norway"
                        },
                        new
                        {
                            Id = new Guid("289e48e9-c338-4003-ae16-370426ff1092"),
                            ImagePath = "images/flags/pakistan.svg",
                            Name = "Pakistan",
                            Slug = "pakistan"
                        },
                        new
                        {
                            Id = new Guid("50527195-f6e0-4a35-8cb1-6257cf471132"),
                            ImagePath = "images/flags/palestine.svg",
                            Name = "Palestine",
                            Slug = "palestine"
                        },
                        new
                        {
                            Id = new Guid("488d2e29-8bf3-4a09-8245-f46e3dc543f5"),
                            ImagePath = "images/flags/panama.svg",
                            Name = "Panama",
                            Slug = "panama"
                        },
                        new
                        {
                            Id = new Guid("684ace13-0121-492d-a6dd-0dc3e3293704"),
                            ImagePath = "images/flags/peru.svg",
                            Name = "Peru",
                            Slug = "peru"
                        },
                        new
                        {
                            Id = new Guid("67ac2314-ed0c-449c-9bcf-0bf65a6d4391"),
                            ImagePath = "images/flags/philippines.svg",
                            Name = "Philippines",
                            Slug = "philippines"
                        },
                        new
                        {
                            Id = new Guid("8cfeb3a2-db28-40b9-b2c5-13d9f6375547"),
                            ImagePath = "images/flags/poland.svg",
                            Name = "Poland",
                            Slug = "poland"
                        },
                        new
                        {
                            Id = new Guid("30f2cb34-b256-409d-a1fb-ae045a2bc94b"),
                            ImagePath = "images/flags/portugal.svg",
                            Name = "Portugal",
                            Slug = "portugal"
                        },
                        new
                        {
                            Id = new Guid("9a052808-fcc3-4cb3-9fcb-e7b02e747021"),
                            ImagePath = "images/flags/qatar.svg",
                            Name = "Qatar",
                            Slug = "qatar"
                        },
                        new
                        {
                            Id = new Guid("3331ed87-8502-4d2f-9812-69682cf6d2e8"),
                            ImagePath = "images/flags/russia.svg",
                            Name = "Russia",
                            Slug = "russia"
                        },
                        new
                        {
                            Id = new Guid("8fee3b9e-1085-46da-a3fd-9207cd11d655"),
                            ImagePath = "images/flags/saudi_arabia.svg",
                            Name = "Saudi Arabia",
                            Slug = "saudi-arabia"
                        },
                        new
                        {
                            Id = new Guid("b8379cf3-b897-4786-8a66-1e6c090441ef"),
                            ImagePath = "images/flags/serbia.svg",
                            Name = "Serbia",
                            Slug = "serbia"
                        },
                        new
                        {
                            Id = new Guid("e9415484-edca-4aad-aca7-515162e940d9"),
                            ImagePath = "images/flags/south_africa.svg",
                            Name = "South Africa",
                            Slug = "south-africa"
                        },
                        new
                        {
                            Id = new Guid("bf4a34e6-497e-4ddb-b535-927734d5841b"),
                            ImagePath = "images/flags/south_korea.svg",
                            Name = "South Korea",
                            Slug = "south-korea"
                        },
                        new
                        {
                            Id = new Guid("bd565c63-0327-4d44-9986-5ee2ef3878bc"),
                            ImagePath = "images/flags/spain.svg",
                            Name = "Spain",
                            Slug = "spain"
                        },
                        new
                        {
                            Id = new Guid("dd43945c-56a8-4216-b1ac-4c3c33d05a11"),
                            ImagePath = "images/flags/sweden.svg",
                            Name = "Sweden",
                            Slug = "sweden"
                        },
                        new
                        {
                            Id = new Guid("f8ec6753-1784-4c82-89e3-e7ea33eb76b0"),
                            ImagePath = "images/flags/thailand.svg",
                            Name = "Thailand",
                            Slug = "thailand"
                        },
                        new
                        {
                            Id = new Guid("72345cda-4598-4dfd-9749-d1b7b13f273f"),
                            ImagePath = "images/flags/trinidad&tobago.svg",
                            Name = "Trinidad & Tobago",
                            Slug = "trinidad-and-tobago"
                        },
                        new
                        {
                            Id = new Guid("cb81bcee-15db-4ff4-afea-d5058210892c"),
                            ImagePath = "images/flags/turkey.svg",
                            Name = "Turkey",
                            Slug = "turkey"
                        },
                        new
                        {
                            Id = new Guid("8fb273a3-c660-426d-8c22-362473781871"),
                            ImagePath = "images/flags/ukraine.svg",
                            Name = "Ukraine",
                            Slug = "ukraine"
                        },
                        new
                        {
                            Id = new Guid("fe6ce064-f562-4f48-bcd4-d98c9aaa37f3"),
                            ImagePath = "images/flags/uae.svg",
                            Name = "UAE",
                            Slug = "united-arab-emirates"
                        },
                        new
                        {
                            Id = new Guid("3c320333-e4a1-4acb-a65e-83b6fb6e9524"),
                            ImagePath = "images/flags/uk.svg",
                            Name = "UK",
                            Slug = "united-kingdom"
                        },
                        new
                        {
                            Id = new Guid("fc61634e-ea99-43d5-9657-26745fc53530"),
                            ImagePath = "images/flags/usa.svg",
                            Name = "USA",
                            Slug = "usa"
                        },
                        new
                        {
                            Id = new Guid("faacc565-75bb-4366-8f43-08b2002d3179"),
                            ImagePath = "images/flags/venezuela.svg",
                            Name = "Venezuela",
                            Slug = "venezuela"
                        },
                        new
                        {
                            Id = new Guid("01578fe3-4933-4153-9ec1-50cd5762a2e8"),
                            ImagePath = "images/flags/vietnam.svg",
                            Name = "Vietnam",
                            Slug = "vietnam"
                        });
                });

            modelBuilder.Entity("foodtopia.Models.HeartedRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HeartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId", "RecipeId")
                        .IsUnique();

                    b.ToTable("HeartedRecipes");
                });

            modelBuilder.Entity("foodtopia.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Measurement")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ff4c97a-1ed7-49fc-8028-b82fee63a446"),
                            Measurement = "cups",
                            Name = "Flour",
                            Quantity = 2m,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8")
                        },
                        new
                        {
                            Id = new Guid("c3834b89-3efd-490f-970a-00e740f7b6a3"),
                            Measurement = "",
                            Name = "Egg",
                            Quantity = 2m,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8")
                        },
                        new
                        {
                            Id = new Guid("2e4b6890-70fb-43d4-af7e-44cb4133ce71"),
                            Measurement = "cup",
                            Name = "Sauce",
                            Quantity = 1m,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8")
                        });
                });

            modelBuilder.Entity("foodtopia.Models.Instruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b29c1c9c-15fa-4a72-b288-3a00bf610453"),
                            Order = 1,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Crack eggs and add to mixing bowl."
                        },
                        new
                        {
                            Id = new Guid("cd48476c-c275-4815-85c8-d2ff52aee99b"),
                            Order = 2,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Whisk until eggs form into a foam-like white texture."
                        },
                        new
                        {
                            Id = new Guid("17419084-b1da-4603-9a36-bd8436b60d79"),
                            Order = 3,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Add arrowroot starch to mixing bowl and other spices of your choosing."
                        },
                        new
                        {
                            Id = new Guid("e192eb4d-9926-4e6e-b274-a55bb6abf58a"),
                            Order = 4,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Place inside the over that has been preheated to 350 degrees Fahrenheit for 8-10 minutes."
                        },
                        new
                        {
                            Id = new Guid("62ae9bf3-85ca-4a5a-b0e3-9f66f87b1f5d"),
                            Order = 5,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Layer the sauce, then the cheese and lastly the toppings."
                        },
                        new
                        {
                            Id = new Guid("60515924-4e5a-4e19-9b6f-86fbfdcc3b12"),
                            Order = 6,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Place back into the over for 12-15 minutes."
                        },
                        new
                        {
                            Id = new Guid("802b167b-f508-43c7-bdf9-e4cf2f49578b"),
                            Order = 7,
                            RecipeId = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            Step = "Let the pizza cool for at least 5 minutes and enjoy!"
                        });
                });

            modelBuilder.Entity("foodtopia.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DifficultyRating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TasteRating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DifficultyAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("DifficultyReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("HeartCount")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TasteAverage")
                        .HasColumnType("numeric");

                    b.Property<int>("TasteReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3968256e-9c61-4415-bfe2-4c1092be12d8"),
                            CountryId = new Guid("fc61634e-ea99-43d5-9657-26745fc53530"),
                            DifficultyAverage = 0m,
                            DifficultyReviewCount = 0,
                            HeartCount = 0,
                            ImageUrl = "images/recipes/low_calorie_pizza.jpg",
                            Name = "Low calorie pizza",
                            PublishedAt = new DateTime(2025, 1, 12, 0, 26, 13, 909, DateTimeKind.Utc).AddTicks(7990),
                            TasteAverage = 0m,
                            TasteReviewCount = 0
                        });
                });

            modelBuilder.Entity("foodtopia.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("character varying(28)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("\"Username\" IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Email = "deleted@placeholder.com",
                            FirstName = "Deleted",
                            IsDeleted = true,
                            LastName = "Deleted",
                            Password = "deleted",
                            Role = "none",
                            Username = "deleted"
                        });
                });

            modelBuilder.Entity("foodtopia.Models.HeartedRecipe", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("HeartedByUsers")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("HeartedRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Ingredient", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodtopia.Models.Instruction", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodtopia.Models.Rating", b =>
                {
                    b.HasOne("foodtopia.Models.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.HasOne("foodtopia.Models.Country", "Country")
                        .WithMany("Recipes")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodtopia.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodtopia.Models.Country", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("foodtopia.Models.Recipe", b =>
                {
                    b.Navigation("HeartedByUsers");

                    b.Navigation("Ingredients");

                    b.Navigation("Instructions");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("foodtopia.Models.User", b =>
                {
                    b.Navigation("HeartedRecipes");

                    b.Navigation("Ratings");

                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
